import { LitElement, PropertyValues } from "lit-element";
declare type Item = {
    value?: string;
    label?: string;
};
declare type RadioButtonProps = {
    className?: string;
    error?: string;
    id?: string;
    itemLayout?: string;
    label?: string;
    value?: string;
    borderVisible?: boolean;
    disabled?: boolean;
    requiredIcon?: boolean;
    visible?: boolean;
    items?: Item[];
};
export declare class RadioButton extends LitElement {
    error: string;
    itemLayout: string;
    label: string;
    value: string;
    borderVisible: boolean;
    disabled: boolean;
    requiredIcon: boolean;
    visible: boolean;
    items: Item[];
    private _labelEl;
    private _selectMenuEl;
    private _inputEls;
    private _GUID;
    constructor(props?: RadioButtonProps);
    private _generateGUID;
    private _updateVisible;
    private _updateContainerWidth;
    private _handleChangeInput;
    private _handleFocusInput;
    private _handleBlurInput;
    private _dispatchCustomEvent;
    createRenderRoot(): this;
    private _getRadioIconSvgTemplate;
    private _getItemTemplate;
    update(changedProperties: PropertyValues): void;
    render(): any;
    updated(): void;
    private _validateItems;
    private _getStyleTagTemplate;
}
export {};
