name: On commit workflow
on:
  push:
jobs:
  Run_tests:
    name: Run unit test
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v0_dev
    - name: Remove package-lock
      run: rm -rf package-lock.json
    - name: Install dependencies
      run: npm install
    - name: Run ESLint
      run: npm run eslint
    - name: Run unit test
      run: npm test
