name: On commit workflow

on:
  push:
jobs:
  Run_tests:
    name: Run unit test
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@main
    - name: Remove package-lock
      run: rm -rf package-lock.json
    - name: Install dependencies
      run: npm install
    - uses: oke-py/npm-audit-action@v1.7.1
      with:
        audit_level: moderate
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        issue_assignees: Pham-Gia-Huong
        issue_labels: vulnerability,test
        dedupe_issues: true
    - name: Run ESLint
      run: npm run es-lint
    - name: Run unit test
      run: npm test
