name: On commit workflow
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  release:
    types: # This configuration does not affect the page_build event above
      - created
jobs:
  Run_tests:
    name: Run unit test
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Remove package-lock
      run: rm -rf package-lock.json
    - name: Install dependencies
      run: npm install
    - name: Run ESLint
      run: npm run lint
    - name: Run unit test
      run: npm test
